### PR TITLE
Change setup configuration for pip

### PR DESCRIPTION
**Pull request by smoia**
This is a proposed internal setup makeover.

## Proposed Changes

  - Add a `setup.cfg` file for pip to better handle the requirements installation
  - Move most of `setup.py` content into `setup.cfg`
  - Remove the packaged `six` and `docopt`, add them as requirements during installation.
  - Update imports to reflect the above-mentioned change
  - Add "extra" modules installation (e.g. `h5py` and `scipy` can be installed with `pip install bioread[hdf5/mat/all]`

## Things that may be interesting to discuss about

  - At the moment, most of the requirements don't have minimal version indication. It might be interesting to add them.
  - `ordereddict` is still packaged, mainly due to the fact that it becomes deprecated with python > 3.6, but then some refactoring is necessary to drop the dependency. It's still a possibility!

### CODE REVIEW

**Comment by smoia** [comment]
Basically, this is what changes:

Schermata da 2020-05-10 21-04-13

**Comment by njvack** [comment]
Hmmmm... it's probably worth dropping ordereddict, and with it the entirety of python2 support. Which means we can also drop six.

Also! It looks like [we might _really_ want a `pyproject.toml` file instead of a `setup.cfg` file[(https://snarky.ca/what-the-heck-is-pyproject-toml/). I could even be talked into the idea that the version number belongs both there and in `_metadata.py` though it makes my soul cry, just a little bit. Though [this](https://stackoverflow.com/questions/60112139/best-way-to-update-package-version-from-pyproject-toml-file) offers some hope — looks like maybe introspecting with `importlib` is a reasonable thing to do?

Anyhow, I'm gonna merge this for now, as it's better than what I'm doing now, and on the right track to being The Right Thing, I think.

**Comment by njvack** [comment]
Well, on a clean vagrant box, after installing I now get:

```
$ acq_info
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/acq_info", line 11, in <module>
    load_entry_point('bioread==1.0.5', 'console_scripts', 'acq_info')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/vagrant/.local/lib/python3.6/site-packages/bioread/__init__.py", line 13, in <module>
    from bioread import reader
  File "/home/vagrant/.local/lib/python3.6/site-packages/bioread/reader.py", line 31, in <module>
    from bioread import headers as bh
  File "/home/vagrant/.local/lib/python3.6/site-packages/bioread/headers.py", line 11, in <module>
    from bioread.struct_dict import StructDict
  File "/home/vagrant/.local/lib/python3.6/site-packages/bioread/struct_dict.py", line 13, in <module>
    from bioread.vendor.ordereddict import OrderedDict
ModuleNotFoundError: No module named 'bioread.vendor'
```

so something is Not Quite Right yet

**Comment by smoia** [comment]
Aw, sorry for that!
It might be because it's not initiating the `vendor` folder. Let me open a second PR.
@rmarkello set up [versioneer](https://github.com/physiopy/phys2bids/blob/master/versioneer.py) for `phys2bids`. We could try to do the same here and drop `_metadata.py`.

Also, I think that the issue with vendor is due to the fact that I accidentally removed the `__init__.py` library from that folder. I can put it back. Would you like to setup a CI to test that these things won't happen?

**Comment by njvack** [comment]
I 100% would love to set up CI, though I haven't done so in yonks and have mostly forgotten how to do it :/

It looks like Github has its own solution for this now?

Also, hi, @rmarkello!

**Comment by njvack** [comment]
Yes it turns out that re-adding __init__.py to vendor/ makes this better, I've just done it.

**Comment by smoia** [comment]
Great, sorry for the bug!
Github does have CI solutions now! We still use Travis and azure (still thanks to our great @rmarkello), but why not stay in house? (Probably there's a reason, but I don't know it)

**Comment by smoia** [comment]
Well, let me know if you cut a release for pypi any time soon, I can't wait to update our installation to make it flawless!

**Comment by njvack** [comment]
It looks like versioneer expects to be making a _version.py file which won't be compatible with updating a pypyroject.toml file... we'll figure something out though

**Comment by njvack** [comment]
Okay! I've upload 1.0.5 to pypi, let me know if it makes life better. There's more stuff to do here, but this might make your life better now.

**Comment by njvack** [comment]
As a little aside: I've set up a CI build with Github Actions and it works a charm. I'm gonna release a 2.0 (only supporting py3.6+) probably today... the last major change to make there is going to be to use pyproject.toml and make setup.py a stub.

**Comment by njvack** [comment]
Okay again! Just FYI, I've yanked 1.0.5 from pypi and replaced it with a full-on 2.0. I figured that a major release was good for the whole "dropping support for a major language version" thing.

Now I am 100% done commenting on this closed PR.

**Pull request merged**
