### PR TITLE
Support for alternative encoding

### PR DESCRIPTION
**Pull request by louis-youpling**
This commit allows support for multiple encoding against UTF-8 only
before. It should solve uwmadison-chm/bioread/#24

### CODE REVIEW

**Comment by njvack** [comment]
Hi!

Thank you so much for the PR!

Would you mind separating the functional changes from the stylistic ones here? I don't want to reformat the project's code at this point, and the formatting changes make it hard to see what's going on.

Also, do you have an example file this allows reading? Adding that (feel free to modify one of the ones in test/data if you can) and a test would be helpful.

Also also, is this fix for python 2, python 3, or both?

**Comment by louis-youpling** [comment]
I have removed the formatting changes. Will add a sample file after removing PHI and associated test. 
This is for python 3.6.7 (Anaconda).

**Comment by njvack** [comment]
Hm... I don't think you need to upload a test file, actually — what this PR probably actually does is switch bioread to a python 3 program?

Are there really AcqKnowledge files with encodings other than UTF-8?

**Comment by louis-youpling** [comment]
See a90f14fa559a17fe392e20d82ceb125df75f5fab.

**Comment by njvack** [comment]
One last thing! Would you bump the version to 1.1.0 with this? I haven't had time to test this locally yet but it's definitely a breaking change.

**Pull request merged**
